bug 5172: more woes with stupid EAI_FOO error codes from getaddrinfo(); it turns out that not only does Cygwin omit some of them, so does FreeBSD 6.1p10.  Work around by using the magic of autoconf for all of: EAI_ADDRFAMILY, EAI_SYSTEM, EAI_NODATA.
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@497460 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/spamc/configure b/spamc/configure
--- a/spamc/configure
+++ b/spamc/configure
@@ -4532,6 +4532,198 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for EAI_ADDRFAMILY" >&5
+echo $ECHO_N "checking for EAI_ADDRFAMILY... $ECHO_C" >&6
+if test "${haveitem+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+                cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <netdb.h>
+int
+main ()
+{
+int foo = EAI_ADDRFAMILY; return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  haveitem=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+haveitem=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext,
+
+fi
+echo "$as_me:$LINENO: result: $haveitem" >&5
+echo "${ECHO_T}$haveitem" >&6
+if test $haveitem = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EAI_ADDRFAMILY 1
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for EAI_SYSTEM" >&5
+echo $ECHO_N "checking for EAI_SYSTEM... $ECHO_C" >&6
+if test "${haveitem+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+                cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <netdb.h>
+int
+main ()
+{
+int foo = EAI_SYSTEM; return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  haveitem=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+haveitem=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext,
+
+fi
+echo "$as_me:$LINENO: result: $haveitem" >&5
+echo "${ECHO_T}$haveitem" >&6
+if test $haveitem = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EAI_SYSTEM 1
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for EAI_NODATA" >&5
+echo $ECHO_N "checking for EAI_NODATA... $ECHO_C" >&6
+if test "${haveitem+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+                cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <sys/socket.h>
+#include <netdb.h>
+int
+main ()
+{
+int foo = EAI_NODATA; return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  haveitem=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+haveitem=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext,
+
+fi
+echo "$as_me:$LINENO: result: $haveitem" >&5
+echo "${ECHO_T}$haveitem" >&6
+if test $haveitem = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EAI_NODATA 1
+_ACEOF
+
+fi
+
 
 # we cheat, since we *know* we have Perl installed ;)
 CCDLFLAGS=`perl -e 'use Config; print $Config::Config{ccdlflags}'`
