we should use the saved test log when generating stats, instead of assuming what's currently in spam-test.log is still usable
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@510008 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/masses/runGA b/masses/runGA
--- a/masses/runGA
+++ b/masses/runGA
@@ -19,12 +19,15 @@ if [ "$NOTE" != "" ]; then
 	LOGDIR="$LOGDIR-$NOTE"
 fi
 
+if [ "x$1" = "x" ]; then
+
+# -------------------------------------------------------------------------
+# Initial rescoring
+
 if [ ! -f "ORIG/ham-$NAME.log" -o ! -f "ORIG/spam-$NAME.log" ]; then
 	echo "Couldn't find logs for $NAME" >&2
 	exit 1
 fi
-
-if [ "x$1" = "x" ]; then
 
 (	# log this
 
@@ -122,13 +125,28 @@ perl ./fp-fn-statistics --ham ham-test.log --spam spam-test.log \
 
 else
 
+# -------------------------------------------------------------------------
 # Statistics generation, once everyone likes the scores
+
+
+  # use the test logs we saved
+  testlogh=$LOGDIR/NSBASE/ham-test.log
+  testlogs=$LOGDIR/SPBASE/spam-test.log
+
+  if [ ! -f "$testlogh" -o ! -f "$testlogs" ]; then
+    echo "Couldn't find logs for $NAME: $testlogh $testlogs" >&2
+    exit 1
+  fi
+
+  rm -f ham-test.log spam-test.log
+  ln -s $testlogh ham-test.log
+  ln -s $testlogs spam-test.log
 
   [ $KILL_SANDBOX_RULES = y ] && rm ../rules/70_sandbox.cf
 
   # This needs to have ../rules/50_scores.cf in place first ...
   echo "[gen test results for set $SCORESET]"
-  perl ./fp-fn-statistics --ham ham-test.log --spam spam-test.log \
+  perl ./fp-fn-statistics --ham $testlogh --spam $testlogs \
       --scoreset $SCORESET --cffile=../rules | tee $LOGDIR/test
 
   echo "[STATISTICS file generation for set $SCORESET]"
