require a minimum of 10 contributors, 150000 ham and 150000 spam mass-check results to generate scores with
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@910811 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/rulesrc/sandbox/dos/new-rule-score-gen/generate-new-scores b/rulesrc/sandbox/dos/new-rule-score-gen/generate-new-scores
--- a/rulesrc/sandbox/dos/new-rule-score-gen/generate-new-scores
+++ b/rulesrc/sandbox/dos/new-rule-score-gen/generate-new-scores
@@ -102,6 +102,24 @@ do
   head $FILE | grep "SVN revision: $REVISION" || rm $FILE
 done
 
+# check to make sure that we have enough corpus submitters
+HAMCONTRIBS=`ls -l corpus/usable-corpus-set$SCORESET/ham-*.log | wc -l | sed -e 's/^[ \t]*//' | cut -d" " -f1`
+SPAMCONTRIBS=`ls -l corpus/usable-corpus-set$SCORESET/spam-*.log | wc -l | sed -e 's/^[ \t]*//' | cut -d" " -f1`
+
+if [ $HAMCONTRIBS -lt 10 ]; then
+  echo "Insufficient ham corpus contributors; aborting."
+  echo " HAM CONTRIBUTORS FOUND: $HAMCONTRIBS (required 10)"
+  echo "SPAM CONTRIBUTORS FOUND: $SPAMCONTRIBS (required 10)"
+  exit 6
+fi
+
+if [ $SPAMCONTRIBS -lt 10 ]; then
+  echo "Insufficient spam corpus contributors; aborting."
+  echo " HAM CONTRIBUTORS FOUND: $HAMCONTRIBS (required 10)"
+  echo "SPAM CONTRIBUTORS FOUND: $SPAMCONTRIBS (required 10)"
+  exit 7
+fi
+
 date
 echo "[ checking out code from svn repository ]"
 
@@ -152,6 +170,25 @@ echo "[ running log-grep-recent ]"
 # only use recent spam to generate scores; use a lot of ham history to avoid FPs
 masses/log-grep-recent -m 38 ../corpus/usable-corpus-set$SCORESET/ham-*.log > masses/ham-full.log
 masses/log-grep-recent -m 2 ../corpus/usable-corpus-set$SCORESET/spam-*.log > masses/spam-full.log
+
+# make sure that we have enough mass-check results to actually generate reasonable scores
+# NOTE: currently we only check for a minimum number of messages
+HAMCOUNT=`wc -l masses/ham-full.log | sed -e 's/^[ \t]*//' | cut -d" " -f1`
+SPAMCOUNT=`wc -l masses/spam-full.log | sed -e 's/^[ \t]*//' | cut -d" " -f1`
+
+if [ $HAMCOUNT -lt 150000 ]; then
+  echo "Insufficient ham corpus to generate scores; aborting."
+  echo " HAM: $HAMCOUNT (150000 required)"
+  echo "SPAM: $SPAMCOUNT (150000 required)"
+  exit 8
+fi
+
+if [ $SPAMCOUNT -lt 150000 ]; then
+  echo "Insufficient spam corpus to generate scores; aborting."
+  echo " HAM: $HAMCOUNT (150000 required)"
+  echo "SPAM: $SPAMCOUNT (150000 required)"
+  exit 9
+fi
 
 # set config to chosen scoreset
 cp masses/config.set$SCORESET masses/config
