corpus-nightly should fall back to 'svn checkout' instead of 'svn update' if that is failing; 'svn co' is more fault-tolerant
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@439644 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/masses/rule-qa/corpus-nightly b/masses/rule-qa/corpus-nightly
--- a/masses/rule-qa/corpus-nightly
+++ b/masses/rule-qa/corpus-nightly
@@ -62,37 +62,31 @@ while true; do
         rm -rf rules    # causing trouble for some reason
         rm -rf rulesrc/sandbox
 
-        # argh svn, messiness
+	if svn update -r $revision < /dev/null && \
+            svn update -r $revision rulesrc < /dev/null
+        then
+		break;
+	fi
+
+        # if that failed, get aggressive about getting a full
+        # checkout, regardless of what may have been here already;
+        # delete most of the checkout to do so, and just use "svn co"
+        # instead of "svn up".
+
+        rm -rf rules lib build rulesrc spamd spamc
         svn cleanup < /dev/null
+        svn co --non-interactive `svnpath` .
 
-	if svn update -r $revision < /dev/null && \
-            svn update -r $revision rulesrc < /dev/null
-        then
-		break;
-	fi
-
-        # TODO: if that failed, we should be just using
-        # a brand new "svn checkout" and forget about the incremental
-        # update niceties
-
-        # OFF: this is extremely antisocial when multiple
-        # corpus-nightly scripts run simultaneously on one CPU!
-	# pkill -TERM svn
-	# sleep 10
-	# pkill -KILL svn
-
-	if svn update -r $revision < /dev/null && \
-            svn update -r $revision rulesrc < /dev/null
-        then
-		break;
-	fi
-
-	if [ $retry -eq 120 ]; then
-		echo "svn update failed" 1>&2
+        # just 10 times; our SVN repo shouldn't be *that* unreliable!
+	if [ $retry -eq 20 ]; then
+		echo "svn update/co failed" 1>&2
 		exit 1
 	fi
+
 	retry=$(( $retry + 1 ))
-	sleep 20
+
+        # longer and longer between retries
+	sleep `expr 20 '*' $retry`
 done
 set -e
 
