attempt to add some decent error-checking to this script
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@897722 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/backend/nitemc/extract_to_rsync_dir b/backend/nitemc/extract_to_rsync_dir
--- a/backend/nitemc/extract_to_rsync_dir
+++ b/backend/nitemc/extract_to_rsync_dir
@@ -4,9 +4,7 @@
 
 RSYNC_DIR=/home/corpus-rsync/tagged_builds
 REPO_URL=http://svn.apache.org/repos/asf/spamassassin/trunk
-REPO2_URL=http://svn.apache.org/repos/asf/spamassassin/rules/trunk
 PERL=/local/perl586/bin/perl
-
 SVN=/opt/subversion-current/bin/svn
 
 type="$1"
@@ -23,6 +21,7 @@ if [ ! -f $versfile ]; then
 fi
 
 subdir=${type}_mass_check
+set -ex
 
 echo "Type: $type"
 echo "Version File: $versfile"
@@ -32,20 +31,29 @@ REV=`tail -1 $versfile | awk '{print $2}'`
 
 echo "Revision: $REV"
 
-# export the main repo:
-rm -rf $RSYNC_DIR/$subdir
-echo Command: $SVN export --non-interactive \
-        -r $REV $REPO_URL $RSYNC_DIR/$subdir
-$SVN export --non-interactive \
-        -r $REV $REPO_URL $RSYNC_DIR/$subdir
+for retry in 1 2 3 4 5 6 7 8 9 10 ; do
 
-cd $RSYNC_DIR/$subdir
-$PERL build/mkrules --out rules > /dev/null
+    # export the main repo:
+    rm -rf $RSYNC_DIR/$subdir
+    echo Command: $SVN export --non-interactive \
+            -r $REV $REPO_URL $RSYNC_DIR/$subdir
+    $SVN export --non-interactive -r $REV $REPO_URL $RSYNC_DIR/$subdir \
+            || continue
 
-# create "svn info" file for mass-check
-# we assume that the current directory was updated via cron to the correct
-# revision, so just info it. (can't do remote info with the svn version
-# installed on the zones machine, nor will it accept "--non-interactive")
-$SVN info $HOME/versions/trunk \
-    > $RSYNC_DIR/$subdir/masses/svninfo.tmp \
-    < /dev/null
+    cd $RSYNC_DIR/$subdir
+    $PERL build/mkrules --out rules > /dev/null || continue
+
+    # create "svn info" file for mass-check
+    # we assume that the current directory was updated via cron to the correct
+    # revision, so just info it. (can't do remote info with the svn version
+    # installed on the zones machine, nor will it accept "--non-interactive")
+    $SVN info $HOME/versions/trunk \
+            > $RSYNC_DIR/$subdir/masses/svninfo.tmp \
+            < /dev/null || continue
+
+    exit               # assume success at this point
+done
+
+echo "FAILED to extract to rsync dir" 1>&2
+exit 2
+
