catch missing svn revision
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@535074 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/build/mkupdates/run_part2 b/build/mkupdates/run_part2
--- a/build/mkupdates/run_part2
+++ b/build/mkupdates/run_part2
@@ -150,6 +150,12 @@ svn copy -m 'promotions validated' . $tagurl < /dev/null
 svnrev=`(grep 'Last Changed Rev: ' $tmpdir/svn || exit 1) | \
         sed -e 's/^.*: //'`
 
+if [ "$svnrev" == "" ] ; then
+  echo "missing SVN revision"
+  cat $tmpdir/svn
+  exit 5
+fi
+
 if [ "$svnrev" -lt 1 ] ; then
   echo "bad SVN revision: $svnrev"
   cat $tmpdir/svn
