bug 6311: add release script to push an immediate rule updates tarball, similar to update-rules script, but based on old run_part2. this should work to release 3.3.1.  update release process README to use it
git-svn-id: https://svn.apache.org/repos/asf/spamassassin/trunk@923169 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/build/mkupdates/update-rules b/build/mkupdates/update-rules
--- a/build/mkupdates/update-rules
+++ b/build/mkupdates/update-rules
@@ -7,6 +7,7 @@
 # no lint problems, etc.  This script simply takes the branch data and creates
 # the update for you.
 #
+# WARNING: this is 3.1 and 3.2 only!
 
 shopt -s nullglob
 
@@ -31,7 +32,10 @@ rm -rf $DIR || exit 1
 if [ "$VERS" = "3.1" -o "$VERS" = "3.2" ] ; then
   SOURCE=svn.apache.org/repos/asf/spamassassin/branches/rules/$VERS
 else
-  SOURCE=svn.apache.org/repos/asf/spamassassin/branches/$VERS/rules
+  echo "ERROR: this script produces broken updates for 3.3; see bug 6311. exiting"
+  exit 99
+
+  # SOURCE=svn.apache.org/repos/asf/spamassassin/branches/$VERS/rules
 fi
 
 tagstamp=`date "+%Y%m%d%H%M%S"`
